name: flutter_auth_package
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
# Fluter SDK
  flutter:
    sdk: flutter

# Cupertino Icons
  cupertino_icons: ^1.0.2

# Firebase Auth(auth)
  firebase_auth: ^3.6.3

# Firebase Cor(connection)
  firebase_core: ^1.20.1

# For User Data storage
  get_storage: ^2.0.3

# For http request
  http: ^0.13.5

# State management
  get: ^4.6.5

# Profile picker
  file_picker: ^5.0.1

# For Connection
  connectivity_plus: ^2.3.6+1

# For Flutter-Toast
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true